[package]
name = "gneiss"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2"
im = "15"
mio = { version = "1.0", features = ["os-poll", "net"] }
num_cpus = "1.16"

[dev-dependencies]
proptest = "1.5"
